import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './utitlities/provider'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DIU Bus Ticket Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <Providers>{children}</Providers>
        <Footer></Footer>
        
        </body>
    </html>
  )
}
